#!/bin/bash

echo "→ Bootstrap steps start here:\n------------------"

echo "→ setup oh-my-zsh"
rm -rf ~/.oh-my-zsh
sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
rm -rf ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
rm -rf ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

echo "→ setup tmux"
rm -rf ~/.tmux/plugins/tpm
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

echo "→ stow"
mv ~/.zshrc ~/.zshrc.bak

stow .
stow --target=$HOME --restow zshrc
stow --target=$HOME --restow git

echo "→ Setting zsh as default shell"
sudo chsh -s $(which zsh) "$USER"

echo "→ Installation complete"
